language: python

python:
    - "3.6"

services: postgresql

env:
    - DJANGO=2.0.6 DB=postgresql
    
before-install:
    - export SECRET_KEY="this_is_the_secret_key"
    
install:
    - pip install -r requirements.txt

before_script:
    - psql -c "CREATE DATABASE test;" -U postgres

script:
    - python manage.py test
    