# Generated by Django 2.0.6 on 2018-07-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reset',
            field=models.BooleanField(default=False),
        ),
    ]
