<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 2.0.6 on 2018-08-08 14:26
=======
# Generated by Django 2.0.6 on 2018-08-08 15:42
>>>>>>> [Chore #59053966] fixed confilcts
=======
# Generated by Django 2.0.6 on 2018-08-09 07:14
>>>>>>> [Chore #59053966] added database tests

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('articles', '0001_initial'),
>>>>>>> [Chore #59053966] fixed confilcts
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('interests', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
                ('follows', models.ManyToManyField(related_name='follower', to='profiles.Profile')),
=======
                ('favorites', models.ManyToManyField(related_name='users_fav_articles', to='articles.Article')),
>>>>>>> [Chore #59053966] fixed confilcts
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
