# Generated by Django 2.0.6 on 2018-07-31 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_birth_date'),
        ('articles', '0003_article_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='profiles.Profile'),
            preserve_default=False,
        ),
    ]
