# Generated by Django 2.0.6 on 2018-08-01 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_birth_date'),
        ('articles', '0005_auto_20180801_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
            preserve_default=False,
        ),
    ]
