# Generated by Django 2.0.6 on 2018-08-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20180801_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='profile',
        ),
    ]
